import type { ImgHTMLAttributes } from "react";

/* ============================================================================
   Logo — RegulonDB brand mark
   ----------------------------------------------------------------------------
   Three variants reference outlined SVG files in src/assets:
     - "wordmark"      : full Regulon + arrow + DB. Use whenever there is room.
     - "wordmark-dark" : white "Regulon", lighter blue arrow. Use over --blue-1.
     - "mark"          : the arrow + DB only. Compact contexts (favicons, nav rail).
   The SVGs were generated by scripts/build-logo.mjs from Arial Black + Arial
   Bold Italic outlines, so they render identically regardless of font
   availability on the consumer.
   ============================================================================ */

import logoUrl       from "../../assets/logo.svg";
import logoOnDarkUrl from "../../assets/logo-on-dark.svg";
import logoMarkUrl   from "../../assets/logo-mark.svg";

export type LogoVariant = "wordmark" | "wordmark-dark" | "mark";

export interface LogoProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, "src" | "alt"> {
  variant?: LogoVariant;
  /** Pixel height; width is computed from the variant's aspect ratio. */
  height?: number;
  /** Optional label override; defaults to "RegulonDB". */
  title?: string;
}

const SRC: Record<LogoVariant, string> = {
  "wordmark":      logoUrl,
  "wordmark-dark": logoOnDarkUrl,
  "mark":          logoMarkUrl,
};

export const Logo = ({
  variant = "wordmark",
  height = 32,
  title = "RegulonDB",
  style,
  ...rest
}: LogoProps) => (
  <img
    src={SRC[variant]}
    alt={title}
    height={height}
    style={{ height, width: "auto", display: "block", ...style }}
    {...rest}
  />
);
